# This viminfo file was generated by Vim 7.4.
# You may edit it if you're careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~H
# Command Line History (newest to oldest):
:q!
|2,0,1467218461,,"q!"
:e /www/zing/main.go
|2,0,1467218427,,"e /www/zing/main.go"
:q
|2,0,1467218308,,"q"

# Search String History (newest to oldest):

# Expression History (newest to oldest):

# Input Line History (newest to oldest):

# Debug Line History (newest to oldest):

# Registers:

# File marks:
'0  1  0  ~/NERD_tree_1
|4,48,1,0,1467218461,"~/NERD_tree_1"

# Jumplist (newest first):
-'  1  0  ~/NERD_tree_1
|4,39,1,0,1467218461,"~/NERD_tree_1"
-'  24  2  ~/NERD_tree_1
|4,39,24,2,1467218414,"~/NERD_tree_1"
-'  1  0  /www/zing/main.go
|4,39,1,0,1467218401,"/www/zing/main.go"

# Buffer list:
%/www/zing/main.go	262	3

# History of marks within files (newest to oldest):

> /www/zing/main.go
	"	262	3
	^	262	4
	.	262	4
	+	262	4

> ~/NERD_tree_1
	"	1	0
	.	1	0
	+	1	0
	+	1	0
	+	1	0
